# 数据库配置
db:
  log_level: "info"
  slow_threshold: 200ms # 慢查询阈值
  ignore_record_not_found_error: true
  # sslmode=disable 用于开发环境，线上一般推荐使用 sslmode=require / sslmode=verify-ca(更高安全性) / sslmode=verify-full (最高安全性)
  sharding:
    - name: "hermet_0"
      dsn: "postgres://jrmarcco:%3Cpasswd%3E@192.168.3.3:15432/hermet_0?sslmode=disable&connect_timeout=1&statement_timeout=3000&idle_in_transaction_session_timeout=3000"
    - name: "hermet_1"
      dsn: "postgres://jrmarcco:%3Cpasswd%3E@192.168.3.3:25432/hermet_1?sslmode=disable&connect_timeout=1&statement_timeout=3000&idle_in_transaction_session_timeout=3000"

