# MongoDB 配置
mongodb:
  uri: "mongodb://192.168.3.3:27017"
  db_name: "hermet"
  app_name: "hermet"

  # 认证信息
  username: "jrmarcco"
  password: "<passwd>"
  auth_source: "admin"

  # 连接池配置
  max_pool_size: 100
  max_conn_idle_time: 10s
  connect_timeout: 1s
  server_selection_timeout: 1s
  startup_timeout: 1s
  shutdown_timeout: 1s

  tls:
    ca: |
      -----BEGIN CERTIFICATE-----
      MIIDSTCCAjGgAwIBAgIUcUyxnveLP7h2ZomRyTosUyhKyDYwDQYJKoZIhvcNAQEL
      BQAwNDETMBEGA1UEAwwKTW9uZ29EQi1DQTEQMA4GA1UECgwHTW9uZ29EQjELMAkG
      A1UEBhMCQ04wHhcNMjUxMjI0MDk0ODM3WhcNMzUxMjIyMDk0ODM3WjA0MRMwEQYD
      VQQDDApNb25nb0RCLUNBMRAwDgYDVQQKDAdNb25nb0RCMQswCQYDVQQGEwJDTjCC
      ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMSr5Uu3/5MsnGtaYozsvJWw
      PYphfo493X81DmD7M5h6cHP9ejlG0XTuULm5SZfmkpfIFHwlRHhMKegUNPjOTLdd
      +veLQYzffpoDW2fHXy0dqiBCO7SJXonH9mEkzfJsf+ZH+FG9DizHlnMWpWaTSUy7
      PQpRnSTa1j8xRYWZjqc0LpSfc8qFdohk3cAWY9rxvt/6QXBcc/MMG2NO3KozOd9s
      Y4eUg0HqVyEmnjJGX/Lw87FbiwsD6Rc2c9poHagTqCBfvSy2tNwu/MV1BGhY7adY
      d2dRxzdW1FOlDpuoS+AwA5xbC54mj/oJYh4B+vHuCs/oPjGuxhAG9sTlJnYPMlsC
      AwEAAaNTMFEwHQYDVR0OBBYEFOvvpLaQR/InG5wi4ziCcUY/M7sSMB8GA1UdIwQY
      MBaAFOvvpLaQR/InG5wi4ziCcUY/M7sSMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZI
      hvcNAQELBQADggEBAGC4E5g0y34wh2gVBDI1FlP1JFgDk2tOuMlLVJyV3oK9o2St
      TWV4D9jfmD2ral5Oz/Qm/YdUqS/NIClMfdMc4cW5CfE1GL0TRT17YnN/X2ZVkTud
      qrwbk2FKitbmwzmIbWxdzrt5VBfghNY6xrpR4rokmhRZWYEDQLcLyuNa4ArQIsEi
      IWJI04sahjtqv1bgabzpkI3kq/y8wmjd3MpBrGKDBOkiqRNz0EgWkmCm+rCSFBMf
      Iz2qPGt5W1ysA90VcYNW+5VI+sPBOu2LoKY/R4o4OAJYNMikmnurf24aG2FRzODR
      UPIspN2/olAJBD4ITqd81nfVgV3FvM8VcKhoHoE=
      -----END CERTIFICATE-----

    cert_key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCX6ir9f9AQoAKP
      50TpJ8sy3XU6XvTnYT2DuozWnp20S7EzKFK2vcOfIVgBs+xrdDil3GTIFwKHal/4
      ysy65oLIn3+jhuKwYczsBqy6GqAZqD9iot5QM0dvlt6PXAFLtZIu0fkXVrE7oNB2
      SWEuF63r4fQxp01pNveK4G8dUrphBIbNfEWvRVryIsy2SriJ6G/6adfUciREtj9i
      19Iq093DVTTFU5wUfJwBylDee+0K6qVipJKQzCT1kqCYdlXXa8dc7W8lGC0ul/oW
      VN0PFxDsNBqjbJzBDHP/00XAM2mJ6farip4dOMNgdswhv4dptq6nUbTX2+axoRSc
      LgS2WunXAgMBAAECggEAS1mccjmDv8NGEg+RqB4TVUrwGwA/dEbQpraQpeFt8qA6
      p9e/0yFj1tnIl6uhQBkZAffDy1VSbU1vhe09SBUO2Kj4O+mrJfaUmJuk7/hF4gQI
      UIndQCV3MNvBz5TAlcddVzjR1ugqp5tX2twBxkV7gE0GfNxxcpcPiIRSyNYgWP8M
      gtqQKFxOu0pjru0pw83oeKAivcbWXFJ08IUgrUmdBDyQR9g0dfGpg78dghaUc1cg
      FE+Wf08YCKS9kJVuh5qfsWNIuWv0P4hdo1/qsvKzDYsB/UNSFH6tPWwRgwsnSepQ
      u7sMSmfH1dogQzzb/0kmodtNf75NDqP4qbPhyukX+QKBgQDMwI+CLa59DHKb3Qaq
      CdAOv1TbFvL5R5b2d7lWbSx8S1zKw62br6QnSwrNxqkU+FNO46v4EqgLmMY7F+Ap
      zOPS2dIw/sNT44QB80L5/wy0HPJfUWiitF7vVRNAiYm2fL9iaM3nEugLPUnLsCdO
      aOCsLXsi0OluMYqH3t6TKNNZvwKBgQC98A+lv/NWoSTqXaPMt8TF35/t3EXisBhJ
      GIceHIqnK6tflIgbtlu9AJ0oZiGl/W72K05YCpbZGwyGGIaV+N+S67T8A872baBS
      iEODTKtt3JvjcXGQPuSXtnZUzQiSNO2aZCt0O+ztyYPnwW4Ub9d+rI5Qs2UtPXNa
      uss2ayKF6QKBgQCHo1yuOULpNhDKbg5XIG8DBf7ZsIc/WgyIs+FEfshEgswyypQ8
      mYteOFks3ljuOl892Jb4nKtUG13ekb9/EWsvJ/sVV//fl83AWP1ajXpF6xMoz85I
      UsK9O5eoXjSrflJuh803MZAkufIkDErNp66GgQ6cjtbEl+8UeTDrPdVdEwKBgQCx
      VWUGl8SV6TYSKwM3q4voQvWKmtIU59yEwoXEs1kw4zDJuF+roALe36fbhB9+XrQu
      2hf3U0urv/ldaaCefRIgljkP4m5k3c2FwPtnpzmXBRX2sIAa8N10WEL6wcNy3j/I
      miWIDDsVd8PTqWEha5qDBpCJADVCm9ELsMLyN+yvoQKBgB7Fsgb3W0EeOM+3Oy7K
      TtF2LCgtLNlzsK/KuS8FAO0iONvHKstcgkhixywy4juaJAcxzZJSnWUdnbJ5OO0y
      Pt6jX/47txYUwSt886MOd8ZgCjvjVxsfOENVMJ8QlP1p3ghDUpxwvgrA8kNf2w8D
      FiaFDnXPRrkDhFIHEKhJyTCr
      -----END PRIVATE KEY-----

    cert_pem: |
      -----BEGIN CERTIFICATE-----
      MIIDjDCCAnSgAwIBAgIUVwOcU/qM7ZlkGql0qvhjRlKowiQwDQYJKoZIhvcNAQEL
      BQAwNDETMBEGA1UEAwwKTW9uZ29EQi1DQTEQMA4GA1UECgwHTW9uZ29EQjELMAkG
      A1UEBhMCQ04wHhcNMjUxMjI0MDk0ODM3WhcNMzUxMjIyMDk0ODM3WjA9MRUwEwYD
      VQQDDAxhZG1pbi1jbGllbnQxFzAVBgNVBAoMDk1vbmdvREItQ2xpZW50MQswCQYD
      VQQGEwJDTjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJfqKv1/0BCg
      Ao/nROknyzLddTpe9OdhPYO6jNaenbRLsTMoUra9w58hWAGz7Gt0OKXcZMgXAodq
      X/jKzLrmgsiff6OG4rBhzOwGrLoaoBmoP2Ki3lAzR2+W3o9cAUu1ki7R+RdWsTug
      0HZJYS4Xrevh9DGnTWk294rgbx1SumEEhs18Ra9FWvIizLZKuInob/pp19RyJES2
      P2LX0irT3cNVNMVTnBR8nAHKUN577QrqpWKkkpDMJPWSoJh2Vddrx1ztbyUYLS6X
      +hZU3Q8XEOw0GqNsnMEMc//TRcAzaYnp9quKnh04w2B2zCG/h2m2rqdRtNfb5rGh
      FJwuBLZa6dcCAwEAAaOBjDCBiTAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYI
      KwYBBQUHAwIwIgYDVR0RBBswGYIMYWRtaW4tY2xpZW50gglsb2NhbGhvc3QwHQYD
      VR0OBBYEFOhRmYQYJqlSFCeVvEftFBqiiaDRMB8GA1UdIwQYMBaAFOvvpLaQR/In
      G5wi4ziCcUY/M7sSMA0GCSqGSIb3DQEBCwUAA4IBAQBYVuibtkPFb+h38GjQlzOH
      wTUZ5rCo6vGgXqRQ7XAbG62rR0kemMDvx55Iex8+159e0daQGkZjfSrLUYFZIfJS
      PmxLFti6cvB/GrPnewrStfDfMqL+wneGpU1K/OQO1ZI3lAVoyGkJRRgtsOjookVN
      e0it4KnQI9KzX6CIjyJhjY593MkxiqvPD01BGZqa2PZPSKr3DtsIBScmc4Em5c74
      KENCB0/2M4/2xD5lo4pPl24PErCA4HZs+yr7Tn+H2OCAsnuDJA8ayzcKj8Vumac7
      IPtFXdJ36zk689PNAM1Jf7uERSAa7fkL0V3qxRamj3F0AuGvg99HQUZxFIGQpqdy
      -----END CERTIFICATE-----


